### ISSUE TITLE
format running list function not working

### ISSUE THREAD

**Issue by mcweenysean** [yjunechoe/Snowglobe#28]
I'm working on this, but it seems that when I try and upload a list of titles to be formatted into a Snowglobe-formatted running list, it does not work. ```uploaded_template({})``` is written as a reactive but then never shows up again in ```server.R```.

I see that you made the commit: remove deprecated template_searched() - still looking into this. Change likely happened with this commit

**Comment by yjunechoe** [comment]
Sorry for this being a late: this involved more technical complications than expected. I'm also spending some time adding styles to new features moving forward so that we don't have to do a complete rewrite of the frontend in one go at the end.

The commit that closed this issue addresses the following:
- The template uploaded back to the "to be formatted" section now gets searched, as intended.
- The filled template is made available for download via another pop-up dialog box
- If any papers are missing (i.e., any rows of the uploaded template could not be filled), the pop-up dialog tells people what the missing rows are and also offer options for dealing with missing rows. The text of these "options" are only partially complete and we can go back to the specific wording of this later. 

Still no guarantee that every single process related to the running list will work properly, but the above changes fixes this specific issue related to "format running list". Ideally, I'd do a complete re-write of all the parts that use the running list (e.g., duplicate checking and updating after search) so I've opened a new issue #29 for that with a list of things that I'm just _assuming_ are still broken and need fixing. I'm going to incrementally work towards this but in the meantime can you help me spot specific problems related to the running list process (ex: duplicates aren't properly removed) with your real-world data? That'll allow me to spend as much of my time as possible on fixing the actual code. If you think there's like a whole bunch of problems such that I should do a total re-write, just bump #29. Thanks!
